travis:
  secure:
    BINSTAR_TOKEN: Axhk4yxORBpJI50yFMMw4Wd4pg3qZbproATIhxWsCahrkCAkkHH0gjgAZOcVmdvnEZgXPoDw00p9rOb9WxjFYyimid3ePAh4fWqGiiysaoADX0NitDiTYvka2ZWhp/2KYhYfgyLgKKqxlGlQnAg3xBAaJfvVfUoXO3t0T9gNFrzU+T2fGqaodgw04X/hH4H7s6F4dwVWb2jbQX3D3P/YdyS/dd1zzNNCyys6Kc+bd4yeFvwjakcLx2RNyGQpdSPwvenQDfL3zJcP2hw3xs3H2guP0QnyiclMmJ8Dgy+ZxlZN7tsJEf1WPu3yA+J++fjUZjvz2CXWM5UQt/sel4gqEtcuu82J0Iq3+V4xvjOCecbLlCjBz13Sr5nlfBM+JhlzdZEGdxYFuvjLX3fIs+WAJzIJv+j89UclwZmkCtuYOfgCpL7fclFXUmHp4pNHf4pU8sHxGZK5j6JbLD67l2XfhipdIWOKaG6vBOM1jLPsNagYw4rtvmyfFe/myxdhtdIXS03hwvbtCQyaMeFkHzk15nIEurXqctzEOVwcDKIwNCNAzLZmsQZb9kvQswQw52E1AapwV6u33/eQYEuyng0VH9OAkiwUZzu01Th4tK9r8zwWKz1NbEdy2kZniKoy1zK7+sW6fwywFkcO2qUaeZR61Lhg96/8T9PMSuDMMXcaRlw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
